services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    init: true
    # env_file: .env  # Uncomment if .env file exists in ./backend
    expose:
      - "5000"  # Flask app default port, as per Dockerfile EXPOSE
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    init: true
    # env_file: .env  # Uncomment if .env file exists in ./frontend
    ports:
      - "5173:4173"  # Map Vite preview server to localhost:5173 as per README
    depends_on:
      - backend  # Frontend likely needs backend API
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
