version: '3.8'

services:
  backend:
    command: python main.py
    volumes:
      - ./backend:/workspace
    environment:
      - FLASK_ENV=development

  frontend:
    command: npm run dev
    volumes:
      - ./frontend:/workspace
      - /workspace/node_modules
    environment:
      - NODE_ENV=development